@rootUrl = http://localhost:8000
#API LIST

###CHECK SERVER STATUS
GET {{rootUrl}}

### User Registration
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fname":"Bhavesh",
    "lname":"Sadhu",
    "email":"bhavesh.sadhu@gmail.com",
    "phone":"0123456789",
    "password":"TesAAa@123"
}

### User Verification from Email
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "token":"1cb97654-f9a9-4d77-949d-dc0094d84587",
    "sessionId":"1cb97654-f9a9-4d77-949d-dc0094d84587"
}

### LOGIN USER
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"bhavesh.sadhu@gmail.com",
    "password":"TesAAaa#$%t@123"
}

### USER PROFILE
GET {{rootUrl}}/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXZlc2guc2FkaHVAZ21haWwuY29tIiwiaWF0IjoxNzQ4MTY4ODk5LCJleHAiOjE3NDgxNjk3OTl9.qUdy0JJp9VpSSvSZwvcIa2zeWa8WlZrs2xqmCYk6fyg

### RENEW ACCESSJWT
GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXZlc2guc2FkaHVAZ21haWwuY29tIiwiaWF0IjoxNzQ4MzQzNjkxLCJleHAiOjE3NTA5MzU2OTF9.DYUg42mmPAGKGDmwDcBoKNIUnfc8bukkZB_UllELc5k