@rootUrl = http://localhost:8000
#API LIST

###CHECK SERVER STATUS
GET {{rootUrl}}

### User Registration
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fname":"Bhavesh",
    "lname":"Sadhu",
    "email":"bhavesh.sadhu@gmail.com",
    "phone":"0123456789",
    "password":"TesAAa@123"
}

### User Verification from Email
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "token":"1cb97654-f9a9-4d77-949d-dc0094d84587",
    "sessionId":"1cb97654-f9a9-4d77-949d-dc0094d84587"
}

### LOGIN USER
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"bhavesh.sadhu@gmail.com",
    "password":"TesAAaa#$%t@123"
}

### USER PROFILE
GET {{rootUrl}}/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXZlc2guc2FkaHVAZ21haWwuY29tIiwiaWF0IjoxNzQ4NDIzMzU4LCJleHAiOjE3NDg0MjQyNTh9.ooEdQxcjWpsgNu5nfSnj8DrRiy-v7IR6JzJWNlRJNXY
### RENEW ACCESSJWT
GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXZlc2guc2FkaHVAZ21haWwuY29tIiwiaWF0IjoxNzQ4NDIzNDI1LCJleHAiOjE3NTEwMTU0MjV9.2QCoKPpC14fW7L_U1oG5qV2gp0ga6wL5yTa_SJsL7TA

### Logout User
GET {{rootUrl}}/api/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJoYXZlc2guc2FkaHVAZ21haWwuY29tIiwiaWF0IjoxNzQ4NDg1ODgyLCJleHAiOjE3NDg0ODY3ODJ9.CArfW7lkIYDyTj9HcZWS5pBe5rly0qjNr5HZmp5hRPY
